In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
stats_df = pd.read_excel(r"P:\Technisch\PLANY PRODUKCJI\PLANIŚCI\PP_TOOLS_TEMP_FILES\15_SAFETY_STOCKS_CALCULATIONS\output\R4_R7_K_ss_summary.xlsx")
stats_df.head()

,plant,material,material_description,lead_time,daily_avg_consumption,daily_avg_cons_stats_only,new_safety_stock,new_ss_range,reorder_point,safety_stock_in_SAP,ss_diff,rop_ss_diff,volatility_method,is_no_ss_item,is_below_min_ss,calculated_new_ss,calculated_new_ROP
0,3701,808965,R79_ 074/118 K200,6,20.0000,15.069,184,9.20,304,252,-68,52,STD,False,False,184,304
1,2101,808965,R79_ 074/118 K200,3,13.2171,12.284,78,5.90,118,200,-122,-82,STD,False,False,78,118
2,2101,839134,R49_ 074/118 K200,3,11.9845,10.352,58,4.84,94,180,-122,-86,STD,False,False,58,94
3,2101,808966,R79_ 074/140 K200,3,9.7907,8.778,57,5.82,87,200,-143,-113,STD,False,False,57,87
4,3701,808966,R79_ 074/140 K200,6,7.3256,5.678,74,10.10,118,100,-26,18,STD,False,False,74,118

In [3]:
zlso_df = pd.read_excel(r"P:\Technisch\PLANY PRODUKCJI\PLANIŚCI\PP_TOOLS_TEMP_FILES\15_SAFETY_STOCKS_CALCULATIONS\input\zlso_table.xlsx", sheet_name='Abf_ZLSO_Aktuell', usecols=['Mat', 'Materialkurztext', 'Land', 'Handbuchlieferzeit'])
zlso_df.head()

       Mat      Materialkurztext Land  Handbuchlieferzeit
0  2024882  R89P 065/098 G200AR2   PL                   0
1  2024883  R89P 065/118 G200AR2   PL                   0
2  2024884  R89P 065/140 G200AR2   PL                   0
3  2024885  R89P 074/098 G200AR2   PL                   0
4  2024886  R89P 074/118 G200AR2   PL                   0

In [4]:
zlso_df['Land_LT_temp'] = (
    zlso_df['Land'].fillna('').astype(str) + " : " + zlso_df['Handbuchlieferzeit'].fillna('').astype(str)
)
zlso_df.head()

       Mat      Materialkurztext Land  Handbuchlieferzeit Land_LT_temp
0  2024882  R89P 065/098 G200AR2   PL                   0       PL : 0
1  2024883  R89P 065/118 G200AR2   PL                   0       PL : 0
2  2024884  R89P 065/140 G200AR2   PL                   0       PL : 0
3  2024885  R89P 074/098 G200AR2   PL                   0       PL : 0
4  2024886  R89P 074/118 G200AR2   PL                   0       PL : 0

In [5]:
zlso_agg = zlso_df.groupby('Mat').agg(
    Land=('Land', lambda x: ', '.join(x.dropna().astype(str))),
    # PriceListLT=('Handbuchlieferzeit', lambda x: ', '.join(x.dropna().astype(str))),
    Land_LT=('Land_LT_temp', lambda x: ', '.join(x[x != " : "])),
    MaxLT=('Handbuchlieferzeit', 'max')
).reset_index()

In [6]:
zlso_agg.head(5)

,Mat,Land,Land_LT,MaxLT
0,251320,PL,PL : 0,0
1,251336,"AT, CH, CZ, DE, FR, HU, IT, NL, PL, SK","AT : 5, CH : 5, CZ : 0, DE : 5, FR : 0, HU : 1...",10
2,252798,"AT, CH, DE, FR, HU, NL, PL","AT : 5, CH : 5, DE : 5, FR : 0, HU : 0, NL : 0...",5
3,252800,"AT, CH, DE, FR, NL, PL","AT : 5, CH : 5, DE : 5, FR : 0, NL : 0, PL : 5",5
4,252807,"AT, CH, CZ, DE, FR, NL, PL, SK","AT : 5, CH : 5, CZ : 0, DE : 5, FR : 10, NL : ...",10

In [15]:
# delivery_plant: list of Lands
DC_to_countries = {'2101': ['PL', 'HU'],
                   '0301': ['DE', 'CH', 'AT', 'IT', 'NL'],
                   '301': ['DE', 'CH', 'AT', 'IT', 'NL'],
                   '1201': ['FR'],
                   '3701': ['CZ', 'SK'],
                   }

In [8]:
# Function to evaluate if stock is required for a given row
def check_stock_needed(row):
    plant = str(row['plant'])

    # Return False if the delivery plant is not present in the dictionary
    if plant not in DC_to_countries:
        return False

    # Get the set of target countries for the given DC
    allowed_countries = set(DC_to_countries[plant])

    # Split the concatenated 'Land' string into individual country codes and strip whitespace
    row_lands = set(land.strip() for land in str(row['Land']).split(',') if land.strip())

    # Return True if there is at least one common country between the two sets
    return bool(allowed_countries & row_lands)

In [9]:
merged_df = pd.merge(stats_df, zlso_agg, left_on='material', right_on='Mat', how='left')

In [10]:
merged_df.head()

,plant,material,material_description,lead_time,daily_avg_consumption,daily_avg_cons_stats_only,new_safety_stock,new_ss_range,reorder_point,safety_stock_in_SAP,...,rop_ss_diff,volatility_method,is_no_ss_item,is_below_min_ss,calculated_new_ss,calculated_new_ROP,Mat,Land,Land_LT,MaxLT
0,3701,808965,R79_ 074/118 K200,6,20.0000,15.069,184,9.20,304,252,...,52,STD,False,False,184,304,808965.0,"CZ, HU, PL, SK","CZ : 0, HU : 10, PL : 2, SK : 0",10.0
1,2101,808965,R79_ 074/118 K200,3,13.2171,12.284,78,5.90,118,200,...,-82,STD,False,False,78,118,808965.0,"CZ, HU, PL, SK","CZ : 0, HU : 10, PL : 2, SK : 0",10.0
2,2101,839134,R49_ 074/118 K200,3,11.9845,10.352,58,4.84,94,180,...,-86,STD,False,False,58,94,839134.0,"CZ, HU, NL, PL, SK","CZ : 0, HU : 0, NL : 0, PL : 0, SK : 0",0.0
3,2101,808966,R79_ 074/140 K200,3,9.7907,8.778,57,5.82,87,200,...,-113,STD,False,False,57,87,808966.0,"CZ, HU, PL, SK","CZ : 0, HU : 10, PL : 2, SK : 0",10.0
4,3701,808966,R79_ 074/140 K200,6,7.3256,5.678,74,10.10,118,100,...,18,STD,False,False,74,118,808966.0,"CZ, HU, PL, SK","CZ : 0, HU : 10, PL : 2, SK : 0",10.0

In [16]:
# Apply the logic across each row in the DataFrame
merged_df['is_stock_needed'] = merged_df.apply(check_stock_needed, axis=1)

In [17]:
merged_df[merged_df['material'] == 496513]

,plant,material,material_description,lead_time,daily_avg_consumption,daily_avg_cons_stats_only,new_safety_stock,new_ss_range,reorder_point,safety_stock_in_SAP,...,volatility_method,is_no_ss_item,is_below_min_ss,calculated_new_ss,calculated_new_ROP,Mat,Land,Land_LT,MaxLT,is_stock_needed
105,2101,496513,R45_ 054/078 K100L5,3,0.2636,0.153,5,18.97,6,14,...,STD,False,False,5,6,496513.0,"HU, PL","HU : 0, PL : 5",5.0,True
800,301,496513,R45_ 054/078 K100L5,5,0.0000,0.000,0,NaN,0,3,...,STD,False,False,0,0,496513.0,"HU, PL","HU : 0, PL : 5",5.0,False
801,1201,496513,R45_ 054/078 K100L5,6,0.0000,0.000,0,NaN,0,0,...,STD,False,True,0,0,496513.0,"HU, PL","HU : 0, PL : 5",5.0,False
802,3701,496513,R45_ 054/078 K100L5,6,0.0000,0.000,0,NaN,0,0,...,STD,False,True,0,0,496513.0,"HU, PL","HU : 0, PL : 5",5.0,False